name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restaurar y Compilar
        run: |
          dotnet restore
          dotnet build --no-restore --configuration Release

      - name: Ejecutar Tests
        run: dotnet test --no-build --configuration Release --verbosity normal
